Import Debian version 0.140ubuntu13.4
initramfs-tools (0.140ubuntu13.4) jammy; urgency=medium

  * hook-functions: add stusb160x kernel module for Tegra IGX (LP: #2027636)

initramfs-tools (0.140ubuntu13.3) jammy; urgency=medium

  [ Loïc Minier ]
  * Include kernel/drivers/usb/typec/ucsi with MODULES=most along with other
    USB storage drivers; LP: #2027636.

  [ Benjamin Drung ]
  * Port the net autopkgtest to the common test framework. This drops
    depending on downloading a cloud image from the Internet and reduces
    the execution time from 3:19 min down to 0:57 min. (LP: #2027575)

diff --git a/debian/tests/test-common b/debian/tests/test-common
--- a/debian/tests/test-common
+++ b/debian/tests/test-common
@@ -1,5 +1,7 @@
 # -*- mode: sh -*-
 
+NICSLOT=5
+
 # Find kernel flavour and release
 KVER=
 for flavour in $SUPPORTED_FLAVOURS; do
@@ -13,7 +15,7 @@ if [ -z "$KVER" ]; then
 	exit 2
 fi
 
-if [ -n "${AUTOPKGTEST_TMP}" ]; then
+if [ -n "${AUTOPKGTEST_TMP-}" ]; then
 	export TMPDIR="${AUTOPKGTEST_TMP}"
 fi
 
@@ -37,8 +39,11 @@ test -n "${ROOTDISK_LINUX_NAME}" || ROOTDISK_LINUX_NAME=vda
 # Create a root fs with a trivial userspace
 ROOTDIR="$(mktemp -d)"
 INIT_MESSAGE='root fs init system started successfully'
-for subdir in bin dev lib proc run sbin sys usr usr/bin; do
+for subdir in dev proc run sys usr usr/bin usr/lib usr/lib64 usr/sbin; do
 	mkdir "${ROOTDIR}/${subdir}"
+done
+for subdir in bin lib lib64 sbin; do
+	ln -s "usr/${subdir}" "${ROOTDIR}/${subdir}"
 done
 cat >"${ROOTDIR}/sbin/init" <<EOF
 #!/bin/sh -e
@@ -86,7 +91,13 @@ build_rootfs_ext2() {
 _run_qemu_amd64() {
 	local extra_params="$*"
 
-	timeout --foreground 60 qemu-system-x86_64 -m 1G -drive "file=${ROOTDISK},if=${ROOTDISK_QEMU_IF},media=disk,format=raw" ${USRDISK:+-drive "file=${USRDISK},if=${USRDISK_QEMU_IF},media=disk,format=raw"} -nographic -no-reboot -kernel "/boot/vmlinuz-${KVER}" -initrd "${INITRAMFS}" -append "root=/dev/${ROOTDISK_LINUX_NAME} ro console=ttyS0,115200 ${extra_params}" | tee "${OUTPUT}"
+	timeout --foreground 60 \
+		qemu-system-x86_64 -m 1G -drive "file=${ROOTDISK},if=${ROOTDISK_QEMU_IF},media=disk,format=raw" \
+		${USRDISK:+-drive "file=${USRDISK},if=${USRDISK_QEMU_IF},media=disk,format=raw"} \
+		-nographic -no-reboot -kernel "/boot/vmlinuz-${KVER}" -initrd "${INITRAMFS}" \
+		-netdev user,id=net0,hostname=goulash,dnssearch=example,dnssearch=example.net,domainname=test,bootfile=/path/to/bootfile \
+		-device virtio-net-pci,netdev=net0,bus=pci.0,addr="$NICSLOT" \
+		-append "root=/dev/${ROOTDISK_LINUX_NAME} ro console=ttyS0,115200 ${extra_params}" | tee "${OUTPUT}"
 }
 
 run_qemu_nocheck_amd64() {
@@ -95,6 +106,14 @@ run_qemu_nocheck_amd64() {
 }
 
 run_qemu_amd64() {
-	_run_qemu_amd64 "panic=-1"
+	_run_qemu_amd64 "panic=-1" "$@"
 	grep -qF "${INIT_MESSAGE}" "${OUTPUT}"
+}
+
+check_output() {
+	local msg="$1"
+	if ! grep -qF "${msg}" "${OUTPUT}"; then
+		echo >&2 "E: Message '${msg}' not found in log output '${OUTPUT}."
+		exit 1
+	fi
 }
